using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;


public enum ActionID
{
    //IMPORTANT NOTE: Do NOT add new values to this enum above any existing values.
    //                Doing so will cause EVERY serialized instance of this enum to be corrupted.
    //                You may still add values under the existing ones.
    GHOST_SWAP,
    PLAYER_LIGHT_ATTACK,
    PLAYER_HEAVY_ATTACK,
    PLAYER_BASIC,
    PLAYER_SPECIAL,
    POLICE_CHIEF_BASIC,
    POLICE_CHIEF_SPECIAL,
    IDOL_BASIC,
    IDOL_SPECIAL,
    SAMURAI_BASIC,
    SAMURAI_SPECIAL,
    SEAMSTRESS_BASIC,
    SEAMSTRESS_SPECIAL,
    PLAGUE_DOCTOR_BASIC,
    PLAGUE_DOCTOR_SPECIAL,
    KING_BASIC,
    KING_SPECIAL,
    MISCELLANEOUS,
    IDOL_SPECIAL_SWAP
}

public enum ActionType
{
    //IMPORTANT NOTE: Do NOT add new values to this enum above any existing values.
    //                Doing so will cause EVERY serialized instance of this enum to be corrupted.
    //                You may still add values under the existing ones.
    LIGHT_ATTACK,
    HEAVY_ATTACK,
    BASIC_ABILITY,
    SPECIAL_ABILITY,
    SKILL,
    SACRIFICE,
    ITEM,
    ENEMY_ATTACK,
    MISCELLANEOUS,
}

public enum DamageStrength
{
    //IMPORTANT NOTE: Do NOT add new values to this enum above any existing values.
    //                Doing so will cause EVERY serialized instance of this enum to be corrupted.
    //                You may still add values under the existing ones.
    MEAGER,
    LIGHT,
    MODERATE,
    HEAVY,
    DEVASTATING,
    MINOR,
}

public enum DamageType
{
    //IMPORTANT NOTE: Do NOT add new values to this enum above any existing values.
    //                Doing so will cause EVERY serialized instance of this enum to be corrupted.
    //                You may still add values under the existing ones.
    MELEE,
    PROJECTILE,
    AREA,
    STATUS,
    ENVIRONMENTAL,
}

public enum GhostID
{
    //IMPORTANT NOTE: Do NOT add new values to this enum above any existing values.
    //                Doing so will cause EVERY serialized instance of this enum to be corrupted.
    //                You may still add values under the existing ones.
    ORION,
    NORTH,
    EVA,
    AKIHITO,
    YUME,
    SILAS,
    KING_AEGIS,
}

/// <summary>
/// Struct that contains context for a damage instance.
/// </summary>
[Serializable]
public struct DamageContext
{
    /// <summary>
    /// The GameObject that is inflicting damage.
    /// </summary>
    [NonSerialized] public GameObject attacker;
    /// <summary>
    /// The GameObject that is receiving damage.
    /// </summary>
    [NonSerialized] public GameObject victim;
    /// <summary>
    /// The amount of damage dealt in this damage instance.
    /// </summary>
    [NonSerialized] public float damage;
    /// <summary>
    /// The damage value of the attack that is causing this damage instance. This might not equal the actual damage dealt.
    /// </summary>
    [NonSerialized] public float trueDamage;
    /// <summary>
    /// An arbitrary value for an attack's power. Useful for determining the strength of effects such as screen shake.
    /// </summary>
    public DamageStrength damageStrength;
    /// <summary>
    /// A list of this damage instance's damage types. Can be relevant for triggering certain gameplay effects.
    /// </summary>
    public List<DamageType> damageTypes;
    /// <summary>
    /// An identifier for the action that is causing this damage instance.
    /// </summary>
    public ActionID actionID;
    /// <summary>
    /// A list of the action types of the action that is causing this damage instance. Can be relevant for triggering certain gameplay effects.
    /// </summary>
    public List<ActionType> actionTypes;
    /// <summary>
    /// A reference to the script that invoked this damage event. Useful for debugging.
    /// </summary>
    [NonSerialized] public object invokingScript;
    /// <summary>
    /// An arbitrary string containing any extra information the user wishes to relay through this damage instance.
    /// </summary>
    public string extraContext;
    /// <summary>
    /// Optional: The point at which a raycast attack hit the collider to trigger the damage effect.
    /// </summary>
    [NonSerialized] public Vector2 raycastHitPosition;
    /// <summary>
    /// An identifier for the Ghost that is causing this damage instance.
    /// </summary>
    public GhostID ghostID;
    /// <summary>
    /// Optional: An icon that is appended to the damage number generated by this damage instance.
    /// </summary>
    [NonSerialized] public Sprite icon;
}

/// <summary>
/// Struct that contains context for a healing instance.
/// </summary>
[Serializable]
public struct HealingContext
{
    /// <summary>
    /// The GameObject that is providing healing.
    /// </summary>
    [NonSerialized] public GameObject healer;
    /// <summary>
    /// The GameObject that is receiving healing.
    /// </summary>
    [NonSerialized] public GameObject healee;
    /// <summary>
    /// The amount of healing provided in this healing instance.
    /// </summary>
    public float healing;
    /// <summary>
    /// The healing value of the action that is causing this healing instance. This might not equal the actual healing dealt.
    /// </summary>
    [NonSerialized] public float trueHealing;
    /// <summary>
    /// An identifier for the action that is causing this healing instance.
    /// </summary>
    public ActionID actionID;
    /// <summary>
    /// A list of the action types of the action that is causing this healing instance. Can be relevant for triggering certain gameplay effects.
    /// </summary>
    public List<ActionType> actionTypes;
    /// <summary>
    /// A reference to the script that invoked this healing event. Useful for debugging.
    /// </summary>
    [NonSerialized] public object invokingScript;
    /// <summary>
    /// An arbitrary string containing any extra information the user wishes to relay through this healing instance.
    /// </summary>
    public string extraContext;
    /// <summary>
    /// An identifier for the Ghost that is causing this healing instance.
    /// </summary>
    public GhostID ghostID;
}

/// <summary>
/// Struct that contains context for an action instance.
/// </summary>
[Serializable]
public struct ActionContext
{
    /// <summary>
    /// An identifier for this action.
    /// </summary>
    public ActionID actionID;
    /// <summary>
    /// A list of the action types of this action. Can be relevant for triggering certain gameplay effects.
    /// </summary>
    public List<ActionType> actionTypes;
    /// <summary>
    /// A reference to the script that invoked this action instance. Useful for debugging.
    /// </summary>
    [NonSerialized] public object invokingScript;
    /// <summary>
    /// An arbitrary string containing any extra information the user wishes to relay through this action instance.
    /// </summary>
    public string extraContext;
}
